name: Deploy to AWS S3

on:
  push:
    branches:
      - test
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: env setting
        run: |
          echo "REACT_APP_TITLE=${{ secrets.REACT_APP_TITLE }}" >> .env
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_TEST_URL }}" >> .env
          echo "REACT_APP_MAIN_COLOR=${{ secrets.REACT_APP_MAIN_COLOR }}" >> .env
          echo "REACT_APP_NAVER_MAP_API=${{ secrets.REACT_APP_NAVER_MAP_API }}" >> .env
          echo "REACT_APP_NAVER_LOCAL_API_URL=${{ secrets.REACT_APP_NAVER_LOCAL_API_URL }}" >> .env
          echo "REACT_APP_NAVER_CLIENT_ID=${{ secrets.REACT_APP_NAVER_CLIENT_ID }}" >> .env
          echo "REACT_APP_NAVER_CLIENT_SECRET=${{ secrets.REACT_APP_NAVER_CLIENT_SECRET }}" >> .env

      - name: Build React
        run: |
          npm install
          CI=false npm run build

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_TEST_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_TEST_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --recursive --region ap-northeast-2 build s3://${{ secrets.AWS_TEST_S3_BUCKET }}
          
